### PR TITLE
Support Python 2.7, 3.3 and 3.4

### PR DESCRIPTION
**Pull request by bradsokol**
Uses the future package to support Python 2.7, 3.3 and 3.4 from a single code base.

Also tested with LCP code base with both unit and integration tests using Python 2.7.

### CODE REVIEW

**Comment by greatestape** [comment]
github says this branch has conflicts

**Comment by bradsokol** [comment]
The conflict is with #43 which is also unmerged. 

Not sure of the GH way of dealing with this? Accept PR #43 and then I can sort out the conflict and push again to this PR?

**Comment by greatestape** [comment]
Done!

**Comment by bradsokol** [comment]
The decrease in coverage is due to Python 2/3 handling such as try/except on imports to handle differences in package names.

Let me know what you'd like me to do with this PR.

**Comment by greatestape** [comment]
Ideally we'd be able to make coveralls look at the aggregate coverage across all different python versions, but I don't think that needs to block this pull request.

**Pull request merged**
